### ISSUE TITLE
Feature: More Statistics

### ISSUE THREAD

**Issue by hno2** [shockbytes/Dante#51]
I would love to have even more statistics including charts. 
My Ideas: 
* Books per Month Chart
* based on Read Pages
  * Most Pages per Day/Month
  * Pages per Day/Month Chart
* BurnDown/Up Charts of the Books Read vs. to read

**Comment by tom2411** [comment]
I really agree

**Comment by shockbytes** [comment]
Hey @hno2 and @tom2411!

Thank you for your suggestions!

The redesigned statistics page should land in the play store soon. It's more visual than the old statistics page. But let me address your suggestions one by one:

* Books per Month Chart --> This is more or less the timeline feature that's already available in the app
* Most pages per day/month, pages per month --> This would require some substantial changes since it's we don't store this information at the moment. I also thought about such statistics, maybe this is included in a later release.
* The burndown / burnup chart sounds fun. Can you elaborate on this idea more?
