### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by airon90** [shockbytes/Dante#62]
[F-Droid](http://f-droid.org) is a FOSS repository of Android apps. I would like that your app would be added in its catalogue. Are you interested in it? By now, I started a request for packaging and you can follow it [here](https://gitlab.com/fdroid/rfp/issues/1133)

**Comment by airon90** [comment]
This request is not compatible because of trackers in the app as stated [here](https://gitlab.com/fdroid/rfp/issues/1133#note_238064514)

**Comment by bitwave** [comment]
The trackers could be removed. Maybe keep this issue open?

**Comment by shockbytes** [comment]
I somehow missed this issue. I'm sorry for that.

However, the app highly depends on Google & Firebase Services. Removing these dependencies is practically infeasible because the core components heavily rely on their functionality. 

I'm sorry but there actually no plans in removing these so-called `trackers` anytime soon.
